version: '3'

services:
  nginx:
      container_name: nginx
      volumes:
      - wordpress_data:/var/www/html
      - mariadb_data:/var/lib/mysql
      networks:
      - inception
      image: nginx
      depends_on:
      - wordpress
      build: requirements/nginx
      env_file: .env
      ports:
        - "443:443"
      restart: on-failure

  mariadb:
      container_name: mariadb
      image: mariadb
      networks:
      - inception
      env_file: .env
      build: requirements/mariadb
      volumes:
      - mariadb_data:/var/lib/mysql
      - wordpress_data:/var/www/html
      restart: on-failure

  wordpress:
      container_name: wordpress
      env_file: .env
      volumes:
      - wordpress_data:/var/www/html
      networks:
      - inception
      image: wordpress
      depends_on:
      - mariadb
      build:
        context: requirements/wordpress
        dockerfile: Dockerfile
      restart: on-failure

volumes:
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nikki/data/wordpress

  mariadb_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/nikki/data/mariadb

networks:
  inception:
   driver: bridge


